/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexion.Conexion;
import java.util.Calendar;
import java.util.GregorianCalendar;
import model.Mdl_Notas;
import controller.Ctr_Notas;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
//import view.VstRecordatorio;

/**
 *
 * @author Joan Hurtado
 */
public class Vw_Notas extends javax.swing.JFrame {

    Ctr_Notas control = new Ctr_Notas();
    Mdl_Notas notas = new Mdl_Notas();

    public Vw_Notas() {
        initComponents();
        mProperties = new Properties();
        this.setLocationRelativeTo(null);
    }
    //Variables para crear el correo
    private String EmailDesde = control.SacarCorreo();
    private static String Contrasena = "jpmlrdetyxuabbxi";
    private String emailPara;
    private String titulo;
    private String Contenido;
    private Properties mProperties;
    private Session mSession;
    private MimeMessage mCorreo;

    public void Enviar() {

        notas.setTipo_nota(String.valueOf(cbbtipodenota1.getSelectedItem()));
        notas.setNota(txtNota.getText());
        notas.setId_nota(control.Auto_increment());
        notas.setHora(control.hora());
        notas.setFecha_registro(control.fechaHoy());

        notas.setEstado("1");
        notas.setTitulo(txttitulo1.getText().toLowerCase().trim());

        if (RbtPrivado.isSelected()) {
            notas.setVisibilidad("1");
        } else {
            notas.setVisibilidad("0");
        }

        if (chkNotificar.isSelected()) {
            crearEmail();
            EnviarEmail();
        }
        //Use un try por si la nota no se envia y poder enviar el mensaje de enviado o no enviados
        try {
            int work = control.BuscarTitulo(notas);
            if (work == 0) {
                control.Guardar(notas);
            } else {
                Limpiar();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nota no enviada hay un error " + e);
        }

        Limpiar();
    }

    public void Limpiar() {
        txttitulo1.setText(" ");

        txtNota.setText("");

        cbbtipodenota1.setSelectedIndex(0);

    }

    private void crearEmail() {
        emailPara = control.SacarCorreo();
        titulo = txttitulo1.getText().trim();
        Contenido = txtNota.getText().trim();

        //protocolo de trasnferencia de email
        mProperties.put("mail.smtp.host", "smtp.gmail.com");
        mProperties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        mProperties.setProperty("mail.smtp.starttls.enable", "true");
        mProperties.setProperty("mail.smtp.port", "587");
        mProperties.setProperty("mail.smtp.users", EmailDesde);
        mProperties.setProperty("mail.smtp.ssl.protocols", "TLSv1.2");
        mProperties.setProperty("mail.smtp.auth", "true");
        mSession = Session.getDefaultInstance(mProperties);

        mCorreo = new MimeMessage(mSession);

        try {
            mCorreo.setFrom(new InternetAddress(EmailDesde));

            mCorreo.setRecipient(Message.RecipientType.TO, new InternetAddress(emailPara));
            mCorreo.setSubject(titulo);
            mCorreo.setText(Contenido, "ISO-8859", "html");

        } catch (AddressException ex) {
            Logger.getLogger(Vw_Notas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(Vw_Notas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnviarEmail() {

        try {
            Transport mTransport = mSession.getTransport("smtp");
            mTransport.connect(EmailDesde, Contrasena);
            mTransport.sendMessage(mCorreo, mCorreo.getRecipients(Message.RecipientType.TO));
            mTransport.close();

            JOptionPane.showMessageDialog(null, "Correo enviado");
        } catch (MessagingException ex) {
            Logger.getLogger(Vw_Notas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        lblEVENTO = new javax.swing.JLabel();
        lblTIPODENOTA = new javax.swing.JLabel();
        lblESTADO = new javax.swing.JLabel();
        lblFECHAREGISTRO = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblTITULO = new javax.swing.JLabel();
        txttitulo = new javax.swing.JTextField();
        txtevento = new javax.swing.JTextField();
        cmbtipodenota = new javax.swing.JComboBox<>();
        txtgrup = new javax.swing.JTextField();
        btnenviar = new javax.swing.JButton();
        txtestado = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        lblescribirmensaje = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnlimpiar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();
        lblescribirmensaje1 = new javax.swing.JLabel();
        cbbtipodenota1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblTIPODENOTA1 = new javax.swing.JLabel();
        lblTITULO1 = new javax.swing.JLabel();
        lblFechaEvento1 = new javax.swing.JLabel();
        btnenviar1 = new javax.swing.JButton();
        txttitulo1 = new javax.swing.JTextField();
        chkNotificar = new javax.swing.JCheckBox();
        RbtPrivado = new javax.swing.JRadioButton();
        RbtPublico = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnVerNotas = new javax.swing.JButton();
        btnRecordatorios = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setAutoRequestFocus(false);
        jFrame1.setBackground(new java.awt.Color(102, 255, 51));

        lblEVENTO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEVENTO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEVENTO.setText("EVENTO");

        lblTIPODENOTA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTIPODENOTA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTIPODENOTA.setText("TIPO DE NOTA");

        lblESTADO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblESTADO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblESTADO.setText("ESTADO");

        lblFECHAREGISTRO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFECHAREGISTRO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFECHAREGISTRO.setText("GRUPO");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setText("NOTIFICAR POR CORREO");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        lblTITULO.setBackground(new java.awt.Color(0, 0, 0));
        lblTITULO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTITULO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTITULO.setText("TITULO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblESTADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblFECHAREGISTRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lblEVENTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTITULO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lblTIPODENOTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEVENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTIPODENOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFECHAREGISTRO)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txttitulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txttitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttituloActionPerformed(evt);
            }
        });

        txtevento.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cmbtipodenota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbtipodenota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de  Nota  ", "1. Nota casual", "2. Nota de Eventos", "3. Nota de Trabajo", "4. Nota de Salud", "5. Nota de Belleza", "6. Nota Escolar", " ", " ", " " }));
        cmbtipodenota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipodenotaActionPerformed(evt);
            }
        });

        txtgrup.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnenviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnenviar.setText("ENVIAR");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        txtestado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });

        btnlimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnlimpiar.setText("Limpiar Informacion");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        lblescribirmensaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblescribirmensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblescribirmensaje.setText("Escribir mensaje");
        lblescribirmensaje.setToolTipText("");

        jRadioButton1.setText("PUBLICO");

        jRadioButton2.setText("PRIVADO");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtevento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbtipodenota, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtgrup, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblescribirmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButton1)
                        .addGap(11, 11, 11)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txtevento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(cmbtipodenota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtgrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnlimpiar)
                            .addComponent(btnenviar)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblescribirmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnlimpiar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnlimpiar1.setText("LIMPIAR");
        btnlimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiar1ActionPerformed(evt);
            }
        });

        txtNota.setColumns(20);
        txtNota.setRows(5);
        jScrollPane2.setViewportView(txtNota);

        lblescribirmensaje1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblescribirmensaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblescribirmensaje1.setText("Escribir Nota");
        lblescribirmensaje1.setToolTipText("");

        cbbtipodenota1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbtipodenota1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de  Nota  ", "Nota casual", "Nota de Eventos", "Nota de Trabajo", "Nota de Salud", "Nota de Belleza", "Nota Escolar", " ", " ", " " }));
        cbbtipodenota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbtipodenota1ActionPerformed(evt);
            }
        });

        lblTIPODENOTA1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblTIPODENOTA1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTIPODENOTA1.setText("TIPO DE NOTA");

        lblTITULO1.setBackground(new java.awt.Color(0, 0, 0));
        lblTITULO1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblTITULO1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTITULO1.setText("TITULO");

        lblFechaEvento1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblFechaEvento1.setText("Tipo de privacidad");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTITULO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTIPODENOTA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblFechaEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 144, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTITULO1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTIPODENOTA1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblFechaEvento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82))
        );

        btnenviar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnenviar1.setText("GUARDAR");
        btnenviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviar1ActionPerformed(evt);
            }
        });

        txttitulo1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txttitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttitulo1ActionPerformed(evt);
            }
        });

        chkNotificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkNotificar.setText("NOTIFICAR POR CORREO");
        chkNotificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNotificarActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbtPrivado);
        RbtPrivado.setText("PRIVADO");
        RbtPrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtPrivadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbtPublico);
        RbtPublico.setText("PUBLICO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txttitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbbtipodenota1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RbtPrivado, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RbtPublico))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnlimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnenviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(chkNotificar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblescribirmensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblescribirmensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(cbbtipodenota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RbtPrivado)
                                    .addComponent(RbtPublico)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnlimpiar1)
                            .addComponent(btnenviar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkNotificar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnVerNotas.setText("Ver Notas");
        btnVerNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerNotasActionPerformed(evt);
            }
        });

        btnRecordatorios.setText("Ver Recordatorios");
        btnRecordatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnVerNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecordatorios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerNotas)
                    .addComponent(btnRecordatorios))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txttituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttituloActionPerformed

    }//GEN-LAST:event_txttituloActionPerformed

    private void cmbtipodenotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipodenotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtipodenotaActionPerformed

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnenviarActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed

    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnlimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiar1ActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnlimpiar1ActionPerformed

    private void txttitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttitulo1ActionPerformed

    }//GEN-LAST:event_txttitulo1ActionPerformed

    private void cbbtipodenota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbtipodenota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbtipodenota1ActionPerformed

    private void chkNotificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNotificarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_chkNotificarActionPerformed

    private void btnenviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviar1ActionPerformed
        // TODO add your handling code here:
        Enviar();
    }//GEN-LAST:event_btnenviar1ActionPerformed

    private void RbtPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtPrivadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtPrivadoActionPerformed

    private void btnVerNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerNotasActionPerformed
        Vw_almacenNotas almacen = new Vw_almacenNotas(this, true);
        almacen.setVisible(true);
    }//GEN-LAST:event_btnVerNotasActionPerformed

    private void btnRecordatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordatoriosActionPerformed
        // TODO add your handling code here:
//        VstRecordatorio recordatorio = new VstRecordatorio();
//        recordatorio.setVisible(true);
    }//GEN-LAST:event_btnRecordatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vw_Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vw_Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vw_Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vw_Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vw_Notas().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtPrivado;
    private javax.swing.JRadioButton RbtPublico;
    private javax.swing.JButton btnRecordatorios;
    private javax.swing.JButton btnVerNotas;
    private javax.swing.JButton btnenviar;
    private javax.swing.JButton btnenviar1;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnlimpiar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbtipodenota1;
    private javax.swing.JCheckBox chkNotificar;
    private javax.swing.JComboBox<String> cmbtipodenota;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblESTADO;
    private javax.swing.JLabel lblEVENTO;
    private javax.swing.JLabel lblFECHAREGISTRO;
    private javax.swing.JLabel lblFechaEvento1;
    private javax.swing.JLabel lblTIPODENOTA;
    private javax.swing.JLabel lblTIPODENOTA1;
    private javax.swing.JLabel lblTITULO;
    private javax.swing.JLabel lblTITULO1;
    private javax.swing.JLabel lblescribirmensaje;
    private javax.swing.JLabel lblescribirmensaje1;
    private javax.swing.JTextArea txtNota;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtevento;
    private javax.swing.JTextField txtgrup;
    private javax.swing.JTextField txttitulo;
    private javax.swing.JTextField txttitulo1;
    // End of variables declaration//GEN-END:variables
}
